'use client';
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n||0));
export default function Dashboard(){
 const [session,setSession]=useState(null),[stocks,setStocks]=useState([]),[mfs,setMfs]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load(data.session.user.id);else setLoading(false)});
 const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)load(s.user.id)});return()=>l.subscription.unsubscribe()},[]);
 async function load(uid){setLoading(true);const [a,b]=await Promise.all([
  supabase.from("holdings").select("id,quantity,invested_value,current_value,unrealized_pnl,pnl_percentage,instruments(symbol,company_name)").eq("user_id",uid),
  supabase.from("mf_holdings").select("id,units,invested_value,current_value,unrealized_pnl,pnl_percentage,mutual_funds(scheme_name,fund_house,category)").eq("user_id",uid)]);
 if(a.error)setError(a.error.message);else setStocks(a.data||[]);if(b.error)setError(v=>v||b.error.message);else setMfs(b.data||[]);setLoading(false)}
 if(!session)return <Login/>;
 const si=stocks.reduce((s,x)=>s+Number(x.invested_value||0),0),sv=stocks.reduce((s,x)=>s+Number(x.current_value||0),0);
 const mi=mfs.reduce((s,x)=>s+Number(x.invested_value||0),0),mv=mfs.reduce((s,x)=>s+Number(x.current_value||0),0),invested=si+mi,value=sv+mv,pnl=value-invested;
 return <main className="shell"><header className="topbar"><div><div className="eyebrow">PORTFOLIO AI</div><h1>Your Portfolio</h1><p>Simple view. Deeper intelligence behind it.</p></div><button onClick={()=>supabase.auth.signOut()}>Sign out</button></header>
 {error&&<div className="error">{error}</div>}<section className="hero card"><div><span className="label">TOTAL PORTFOLIO</span><div className="heroValue">{money(value)}</div><div className={pnl>=0?"positive":"negative"}>{money(pnl)} ({invested?(pnl/invested*100).toFixed(2):"0.00"}%)</div></div><div className="goal"><span className="label">₹9 CRORE GOAL</span><strong>{(value/90000000*100).toFixed(2)}%</strong><div className="bar"><span style={{width:`${Math.min(value/90000000*100,100)}%`}}/></div></div></section>
 <section className="grid two"><div className="card"><span className="label">STOCKS</span><h2>{money(sv)}</h2><p>Invested {money(si)}</p><div className={sv-si>=0?"positive":"negative"}>P/L {money(sv-si)}</div></div><div className="card"><span className="label">MUTUAL FUNDS</span><h2>{money(mv)}</h2><p>Invested {money(mi)}</p><div className={mv-mi>=0?"positive":"negative"}>P/L {money(mv-mi)}</div></div></section>
 <section className="card"><span className="label">STOCK HOLDINGS</span><h2>{stocks.length} positions</h2>{loading?<p>Loading...</p>:<table><thead><tr><th>Stock</th><th>Qty</th><th>Invested</th><th>Value</th><th>P/L</th></tr></thead><tbody>{stocks.map(x=><tr key={x.id}><td><b>{x.instruments?.symbol||"—"}</b><small>{x.instruments?.company_name||""}</small></td><td>{Number(x.quantity).toLocaleString("en-IN")}</td><td>{money(x.invested_value)}</td><td>{money(x.current_value)}</td><td className={Number(x.unrealized_pnl)>=0?"positive":"negative"}>{money(x.unrealized_pnl)}</td></tr>)}</tbody></table>}</section>
 <section className="card"><span className="label">MUTUAL FUNDS</span><h2>{mfs.length} positions</h2>{loading?<p>Loading...</p>:<table><thead><tr><th>Fund</th><th>Units</th><th>Invested</th><th>Value</th><th>P/L</th></tr></thead><tbody>{mfs.map(x=><tr key={x.id}><td><b>{x.mutual_funds?.scheme_name||"—"}</b><small>{x.mutual_funds?.fund_house||""}</small></td><td>{Number(x.units).toLocaleString("en-IN",{maximumFractionDigits:3})}</td><td>{money(x.invested_value)}</td><td>{money(x.current_value)}</td><td className={Number(x.unrealized_pnl)>=0?"positive":"negative"}>{money(x.unrealized_pnl)}</td></tr>)}</tbody></table>}</section></main>
}
function Login(){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState("");
async function go(e){e.preventDefault();setError("");const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message)}
return <main className="login"><form className="card loginCard" onSubmit={go}><div className="eyebrow">PORTFOLIO AI</div><h1>Your money. One screen.</h1><p>Sign in to view your consolidated portfolio.</p><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div className="error">{error}</div>}<button className="primary">Sign in</button></form></main>}