import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
export const dynamic="force-dynamic";
export const maxDuration=300;
const ENGINE_VERSION="decision_validation_v1_2";
const SCORE_VERSION="ai_scorer_v5_5";
const V3="https://api.upstox.com/v3",V2="https://api.upstox.com/v2";
const admin=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null;};
function authorized(request){const p=process.env.PIPELINE_SECRET||"",c=process.env.CRON_SECRET||"",a=request.headers.get("authorization")||"";return !!((p&&(request.headers.get("x-pipeline-secret")===p||a===`Bearer ${p}`))||(c&&a===`Bearer ${c}`));}
async function fetchJson(url,token){const r=await fetch(url,{headers:{Accept:"application/json",Authorization:`Bearer ${token}`},cache:"no-store"});const text=await r.text();let body={};try{body=JSON.parse(text);}catch{}return{ok:r.ok,status:r.status,body};}
async function resolveKey(isin,token){const clean=String(isin||"").trim().toUpperCase();if(!clean)return null;const r=await fetchJson(`${V2}/instruments/search?query=${encodeURIComponent(clean)}&exchanges=NSE&segments=EQ&instrument_types=EQ&page_number=1&records=30`,token);const rows=Array.isArray(r.body?.data)?r.body.data:[];const m=rows.find(x=>String(x?.isin||"").toUpperCase()===clean&&String(x?.segment||"").toUpperCase()==="NSE_EQ");return m?.instrument_key||null;}
const iso=v=>new Date(v).toISOString().slice(0,10);
function pick(candles,snapshot,days){const snap=new Date(snapshot).getTime();const future=candles.map(c=>({t:new Date(c[0]).getTime(),close:n(c[4])})).filter(x=>x.t>snap&&x.close!=null).sort((a,b)=>a.t-b.t);return future[days-1]||null;}
async function candlesFor(isin,snapshot,token){let key=`NSE_EQ|${String(isin||"").trim().toUpperCase()}`;const to=new Date(),from=new Date(snapshot);from.setUTCDate(from.getUTCDate()-2);const get=k=>fetchJson(`${V3}/historical-candle/${encodeURIComponent(k)}/days/1/${iso(to)}/${iso(from)}`,token);let r=await get(key),candles=Array.isArray(r.body?.data?.candles)?r.body.data.candles:[];if(!candles.length){const resolved=await resolveKey(isin,token);if(resolved){r=await get(resolved);candles=Array.isArray(r.body?.data?.candles)?r.body.data.candles:[];}}return{candles,status:r.status};}
async function evaluate(row,instrument,token){if(row.reference_price==null||!instrument?.isin)return{id:row.id,status:"NO_REFERENCE_PRICE"};const {candles,status}=await candlesFor(instrument.isin,row.snapshot_at,token);if(!candles.length)return{id:row.id,status:`MARKET_DATA_${status||"UNAVAILABLE"}`};const out={id:row.id};for(const [days,field,at] of [[5,"return_5d_pct","evaluated_5d_at"],[20,"return_20d_pct","evaluated_20d_at"],[60,"return_60d_pct","evaluated_60d_at"]]){const point=pick(candles,row.snapshot_at,days);if(point){out[field]=+(((point.close-Number(row.reference_price))/Number(row.reference_price))*100).toFixed(4);out[at]=new Date(point.t).toISOString();}}const done=[out.return_5d_pct,out.return_20d_pct,out.return_60d_pct].filter(v=>v!=null).length;out.outcome_status=done===3?"COMPLETE":done?"PARTIAL":"PENDING";return out;}
export async function GET(request){if(!authorized(request))return NextResponse.json({success:false,engine_version:ENGINE_VERSION,error:"Unauthorized"},{status:401});const started=Date.now();try{const [{data:rows,error:le},{data:instruments,error:ie}]=await Promise.all([admin.from("decision_validation_ledger").select("id,instrument_id,snapshot_at,reference_price,return_5d_pct,return_20d_pct,return_60d_pct").eq("score_version",SCORE_VERSION).order("snapshot_at",{ascending:true}).limit(5000),admin.from("instruments").select("id,isin")]);if(le)throw le;if(ie)throw ie;const token=process.env.UPSTOX_ANALYTICS_TOKEN;if(!token)throw new Error("UPSTOX_ANALYTICS_TOKEN is missing.");const im=new Map((instruments||[]).map(x=>[x.id,x]));const work=(rows||[]).filter(r=>r.reference_price!=null&&(r.return_5d_pct==null||r.return_20d_pct==null||r.return_60d_pct==null));let results=[];for(let i=0;i<work.length;i+=5)results.push(...await Promise.all(work.slice(i,i+5).map(r=>evaluate(r,im.get(r.instrument_id),token))));let updated=0;for(const r of results){const patch={outcome_status:r.outcome_status||r.status||"PENDING"};for(const k of ["return_5d_pct","return_20d_pct","return_60d_pct","evaluated_5d_at","evaluated_20d_at","evaluated_60d_at"])if(r[k]!=null)patch[k]=r[k];const {error}=await admin.from("decision_validation_ledger").update(patch).eq("id",r.id);if(!error)updated++;else console.error("Outcome update error",r.id,error);}const summary={rows_considered:work.length,rows_updated:updated,complete:results.filter(x=>x.outcome_status==="COMPLETE").length,partial:results.filter(x=>x.outcome_status==="PARTIAL").length,pending:results.filter(x=>x.outcome_status==="PENDING").length,elapsed_ms:Date.now()-started};return NextResponse.json({success:true,engine_version:ENGINE_VERSION,score_version:SCORE_VERSION,summary});}catch(error){console.error("Decision validation evaluation error:",error);return NextResponse.json({success:false,engine_version:ENGINE_VERSION,error:error?.message||"Validation evaluation failed."},{status:500});}}
