import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { scoreStock } from "../../lib/scoring/ai-scorer-v5-0";
import { normalizeSector } from "../../lib/scoring/sector-normalization";

export const dynamic = "force-dynamic";
export const maxDuration = 120;
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL;
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const ENGINE_VERSION="ai_scorer_v5_2_preview";
const TARGETS=[
 {label:"BIOCON",aliases:["BIOCON"]},{label:"PRAJ INDUSTRIES",aliases:["PRAJ INDUSTRIES","PRAJ INDUSTRIES LTD"]},{label:"INDUSIND BANK",aliases:["INDUSIND BANK","INDUSIND BANK LIMITED"]},{label:"LAURUS LABS",aliases:["LAURUS LABS","LAURUS LABS LIMITED"]},{label:"BHARAT ELECTRONICS",aliases:["BHARAT ELECTRONICS","BHARAT ELECTRONICS LTD"]},{label:"GARDEN REACH SHIPBUILDERS",aliases:["GARDEN REACH SHIPBUILDERS","GARDEN REACH SHIP&ENG LTD"]},{label:"MOTHERSON SUMI WIRING",aliases:["MOTHERSON SUMI WIRING","MOTHERSON SUMI WRNG IND L"]}
];
function admin(){if(!SUPABASE_URL||!KEY)throw new Error("Supabase service configuration is missing.");return createClient(SUPABASE_URL,KEY,{auth:{autoRefreshToken:false,persistSession:false}});}
async function authorized(request){const secret=process.env.PIPELINE_SECRET||"",header=request.headers.get("x-pipeline-secret")||"",auth=request.headers.get("authorization")||"";if(secret&&(header===secret||auth===`Bearer ${secret}`))return true;const bearer=auth.startsWith("Bearer ")?auth.slice(7):"";if(!bearer)return false;try{const {data,error}=await admin().auth.getUser(bearer);return !error&&!!data?.user;}catch{return false;}}
function norm(v){return String(v||"").trim().toUpperCase().replace(/[^A-Z0-9]+/g," ").trim();}
function matches(row,target){const values=[row?.symbol,row?.company_name,row?.name].map(norm).filter(Boolean);return target.aliases.map(norm).some(t=>values.some(v=>v===t||v.includes(t)||t.includes(v)));}
async function technicalFor(request,isin){if(!isin)return{available:false,reason:"Missing ISIN."};const origin=new globalThis.URL(request.url).origin;const response=await fetch(`${origin}/api/market-intelligence?isin=${encodeURIComponent(isin)}&days=365`,{headers:{"x-pipeline-secret":process.env.PIPELINE_SECRET||""},cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error||`Market intelligence failed (${response.status}).`);return body?.technical||{available:false,reason:"Technical response missing."};}
async function marketRegimeFor(request){const origin=new globalThis.URL(request.url).origin;const response=await fetch(`${origin}/api/market-regime`,{headers:{"x-pipeline-secret":process.env.PIPELINE_SECRET||""},cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok||!body?.success||!body?.regime?.label)throw new Error(body?.error||`Market regime failed (${response.status}).`);return body.regime;}
export async function GET(request){if(!(await authorized(request)))return NextResponse.json({success:false,error:"Unauthorized"},{status:401});try{const supabase=admin(),marketRegime=await marketRegimeFor(request);const [{data:instruments,error:ie},{data:fundamentals,error:fe},{data:scores,error:se}]=await Promise.all([supabase.from("instruments").select("*").limit(5000),supabase.from("fundamentals").select("*").limit(5000),supabase.from("ai_scores").select("instrument_id,total_score").limit(5000)]);if(ie)throw ie;if(fe)throw fe;if(se)throw se;const byInstrument=new Map((instruments||[]).map(x=>[x.id||x.instrument_id,x])),fundBy=new Map((fundamentals||[]).map(x=>[x.instrument_id,x])),legacy=new Map((scores||[]).map(x=>[x.instrument_id,x.total_score])),allFundamentals=fundamentals||[],results=[];
for(const target of TARGETS){const instrument=(instruments||[]).find(x=>matches(x,target));if(!instrument){results.push({company:target.label,error:"Instrument not found in database."});continue;}const instrumentId=instrument.id||instrument.instrument_id,f=fundBy.get(instrumentId);if(!f){results.push({company:instrument.company_name||target.label,error:"Fundamentals not found in database."});continue;}const sector=normalizeSector(instrument.sector||f.sector||"OTHER"),peers=allFundamentals.filter(x=>{const p=byInstrument.get(x.instrument_id);return p&&normalizeSector(p.sector||"OTHER")===sector;});try{const technical=await technicalFor(request,instrument.isin);const currentPrice=Number.isFinite(Number(technical?.current_price))?Number(technical.current_price):Number.isFinite(Number(technical?.ltp))?Number(technical.ltp):Number.isFinite(Number(instrument?.current_price))?Number(instrument.current_price):Number.isFinite(Number(instrument?.ltp))?Number(instrument.ltp):null;const scored=scoreStock({fundamentals:f,peers,technical,regime:marketRegime.label,sector,currentPrice});results.push({company:instrument.company_name||instrument.name||target.label,symbol:instrument.symbol||null,instrument_id:instrumentId,sector,peer_count:peers.length,legacy_total_score:legacy.get(instrumentId)??null,current_price:currentPrice,...scored,regime_used:marketRegime.label});}catch(error){results.push({company:instrument.company_name||target.label,instrument_id:instrumentId,sector,error:error?.message||"Scoring failed."});}}
return NextResponse.json({success:true,engine_version:ENGINE_VERSION,dry_run:true,writes_performed:false,architecture:{primary:"LT Investment Quality",secondary:"ST Market Setup",risk:"Separate risk signal",valuation:"Metrics + indicative peer-multiple fair value"},market_regime:marketRegime,targets:TARGETS.map(x=>x.label),results,generated_at:new Date().toISOString()});}catch(error){return NextResponse.json({success:false,engine_version:ENGINE_VERSION,error:error?.message||"Preview failed."},{status:500});}}
