import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { scoreStock } from "../../lib/scoring/ai-scorer-v5-5";
import { normalizeSector } from "../../lib/scoring/sector-normalization";
import { calculateMarketRegime } from "../../lib/market-regime";
import { getTechnicalForIsin } from "../../lib/upstox-technical";

export const dynamic="force-dynamic";
export const maxDuration=120;
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL;
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const UPSTOX_BASE="https://api.upstox.com/v2";
const TARGETS=["BIOCON","PRAJ INDUSTRIES","INDUSIND BANK","LAURUS LABS","BHARAT ELECTRONICS","GARDEN REACH SHIPBUILDERS","MOTHERSON SUMI WIRING"];
const BANKING=new Set(["BANKING","NBFC","FINANCIAL_SERVICES"]);
function admin(){if(!SUPABASE_URL||!KEY)throw new Error("Supabase service configuration is missing.");return createClient(SUPABASE_URL,KEY,{auth:{autoRefreshToken:false,persistSession:false}});}
async function authorized(request){const secret=process.env.PIPELINE_SECRET||"",header=request.headers.get("x-pipeline-secret")||"",auth=request.headers.get("authorization")||"";if(secret&&(header===secret||auth===`Bearer ${secret}`))return true;const bearer=auth.startsWith("Bearer ")?auth.slice(7):"";if(!bearer)return false;try{const {data,error}=await admin().auth.getUser(bearer);return !error&&!!data?.user;}catch{return false;}}
async function upstox(path){const token=process.env.UPSTOX_ANALYTICS_TOKEN;if(!token)throw new Error("Missing UPSTOX_ANALYTICS_TOKEN");const r=await fetch(`${UPSTOX_BASE}${path}`,{headers:{Accept:"application/json",Authorization:`Bearer ${token}`},cache:"no-store"});return{ok:r.ok,status:r.status,body:await r.json().catch(()=>null)};}
const norm=v=>String(v||"").trim().toUpperCase().replace(/[^A-Z0-9]+/g," ").trim();
function ratioRows(body){const rows=Array.isArray(body?.data)?body.data:[];return rows.map(x=>({name:String(x?.name||""),company_value:x?.company_value??null,sector_value:x?.sector_value??null,company_numeric:Number.parseFloat(String(x?.company_value??"").replace(/[%₹,]/g,"")),sector_numeric:Number.parseFloat(String(x?.sector_value??"").replace(/[%₹,]/g,""))})).filter(x=>x.name).map(x=>({...x,company_numeric:Number.isFinite(x.company_numeric)?x.company_numeric:null,sector_numeric:Number.isFinite(x.sector_numeric)?x.sector_numeric:null}));}
function ratioMap(rows){const out={};for(const row of rows||[]){const k=norm(row.name);if(k==="P E")out.pe=row;else if(k==="P B")out.pb=row;else if(k==="ROA")out.roa=row;else if(k==="ROE")out.roe=row;else if(k==="ROCE")out.roce=row;else if(k==="EV EBITDA")out.ev_ebitda=row;}return out;}
function matches(i,target){return [i?.symbol,i?.company_name,i?.name].map(norm).filter(Boolean).some(v=>v===norm(target)||v.includes(norm(target))||norm(target).includes(v));}
function quality(scored,technical){const reasons=[];if(!technical?.available)reasons.push(technical?.reason||"Technical market data unavailable");if(scored?.unavailable?.length)reasons.push(...scored.unavailable);return{data_status:reasons.length?"LIMITED":"GOOD",unavailable_reasons:[...new Set(reasons)]};}
export async function GET(request){if(!(await authorized(request)))return NextResponse.json({success:false,error:"Unauthorized"},{status:401});try{const s=admin(),regime=await calculateMarketRegime();const [{data:instruments,error:ie},{data:fundamentals,error:fe},{data:history,error:he}]=await Promise.all([s.from("instruments").select("*").limit(5000),s.from("fundamentals").select("*").limit(5000),s.from("fundamentals_history").select("*").order("period",{ascending:true}).limit(10000)]);if(ie)throw ie;if(fe)throw fe;if(he)throw he;const im=new Map((instruments||[]).map(x=>[x.id,x])),fm=new Map((fundamentals||[]).map(x=>[x.instrument_id,x])),hm=new Map();for(const h of history||[]){if(!hm.has(h.instrument_id))hm.set(h.instrument_id,[]);hm.get(h.instrument_id).push(h);}const results=[];for(const target of TARGETS){const i=(instruments||[]).find(x=>matches(x,target));if(!i){results.push({company:target,data_status:"UNAVAILABLE",unavailable_reasons:["Instrument not found"]});continue;}const f=fm.get(i.id);if(!f){results.push({company:i.company_name||target,data_status:"UNAVAILABLE",unavailable_reasons:["Fundamentals not found"]});continue;}try{const sector=normalizeSector(i.sector||f.sector||"OTHER"),peers=(fundamentals||[]).filter(x=>{const p=im.get(x.instrument_id);return p&&normalizeSector(p.sector||"OTHER")===sector;}),technical=await getTechnicalForIsin(i.isin,365),currentPrice=Number.isFinite(Number(technical?.price))?Number(technical.price):null;let bankingRows=[];if(BANKING.has(sector)){const rr=await upstox(`/fundamentals/${encodeURIComponent(i.isin)}/key-ratios`);bankingRows=ratioRows(rr.body);}const bankingRatios=ratioMap(bankingRows),scored=scoreStock({fundamentals:f,peers,technical,regime:regime.regime.label,sector,currentPrice,history:hm.get(i.id)||[],bankingRatios}),q=quality(scored,technical);results.push({company:i.company_name||i.name||target,symbol:i.symbol||null,instrument_id:i.id,sector,history_periods:(hm.get(i.id)||[]).length,current_price:currentPrice,technical_status:technical?.status||"AVAILABLE",technical_reason:technical?.reason||null,technical_source:technical?.data_source||null,banking_ratios:bankingRows,provider_ratios_used:Object.keys(bankingRatios),...q,...scored,regime_used:regime.regime.label});}catch(e){results.push({company:i.company_name||i.name||target,symbol:i.symbol||null,instrument_id:i.id,sector:normalizeSector(i.sector||f.sector||"OTHER"),data_status:"ERROR",unavailable_reasons:[e?.message||"Stock scoring failed"]});}}
return NextResponse.json({success:true,engine_version:"ai_scorer_v5_5_preview",dry_run:true,writes_performed:false,market_regime:regime.regime,targets:TARGETS,results,generated_at:new Date().toISOString()});}catch(e){return NextResponse.json({success:false,engine_version:"ai_scorer_v5_5_preview",error:e?.message||"V5.5 preview failed."},{status:500});}}
